name: "Multi Arch"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter version'
        required: true
        default: '1.0.0'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-actions@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-actions@v2
